### ISSUE TITLE
Export not working in v0.3.4

### ISSUE THREAD

**Issue by shivam124081** [redbrick-ai/redbrick-sdk#31]
I am referring to the syntax in the documentation - https://docs.redbrickai.com/python-sdk/export. 

`from redbrick.export import Export` returns the following error: 
```
Traceback (most recent call last):
  File "export.py", line 2, in <module>
    from redbrick.export import Export
ImportError: cannot import name 'Export' from 'redbrick.export' (/Users/shivamsharma/Documents/RedBrick/Technical/demos/env/lib/python3.7/site-packages/redbrick/export/__init__.py)
```
<hr />

Also `DatapointCreator` isn't there in v0.3.4

**Comment by GioRdrz** [comment]
Fixed on 0.3.5 version
